# Generated by Django 3.2.18 on 2023-06-14 03:46

# from django.db import migrations, models
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ("audit_log", "0015_alter_logentry_changes"),
#     ]
#
#     operations = [
#         migrations.AddField(
#             model_name="logentry",
#             name="db_user",
#             field=models.CharField(blank=True, max_length=50, null=True),
#         ),
#         migrations.AlterField(
#             model_name="logentry",
#             name="actor",
#             field=models.JSONField(blank=True, null=True),
#         ),
#     ]